services:
  - type: web
    name: weatherapp
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn WeatherApp.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: your_project_name.settings