services:
  - type: web
    name: weatherapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && python manage.py collectstatic --noinput && gunicorn WeatherApp.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: WeatherApp.settings
