# Generated by Django 5.2.4 on 2025-07-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_alter_thought_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thought",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
